import {Employee} from "./types";

export default [
  {id: 1, name: "Иван", lastName: "Иванов", companyId: 7, post: "Разработчик"},
  {id: 2, name: "Елена", lastName: "Петрова", companyId: 3, post: "Менеджер"},
  {id: 3, name: "Александр", lastName: "Смирнов", companyId: 5, post: "Дизайнер"},
  {id: 4, name: "Ольга", lastName: "Морозова", companyId: 2, post: "Тестировщик"},
  {id: 5, name: "Сергей", lastName: "Кузнецов", companyId: 1, post: "Аналитик"},
  {id: 6, name: "Наталья", lastName: "Васильева", companyId: 8, post: "Маркетолог"},
  {id: 7, name: "Алексей", lastName: "Попов", companyId: 4, post: "Программист"},
  {id: 8, name: "Татьяна", lastName: "Соколова", companyId: 3, post: "Администратор"},
  {id: 9, name: "Дмитрий", lastName: "Лебедев", companyId: 6, post: "Архитектор"},
  {id: 10, name: "Екатерина", lastName: "Новикова", companyId: 9, post: "Технический писатель"},
  {id: 11, name: "Ирина", lastName: "Козлова", companyId: 2, post: "Техподдержка"},
  {id: 12, name: "Павел", lastName: "Морозов", companyId: 8, post: "Продюсер"},
  {id: 13, name: "Мария", lastName: "Петрова", companyId: 4, post: "Дизайнер"},
  {id: 14, name: "Андрей", lastName: "Волков", companyId: 5, post: "Менеджер проекта"},
  {id: 15, name: "Светлана", lastName: "Смирнова", companyId: 10, post: "Аналитик"},
  {id: 16, name: "Виктор", lastName: "Захаров", companyId: 1, post: "Инженер"},
  {id: 17, name: "Анна", lastName: "Павлова", companyId: 3, post: "Рекрутер"},
  {id: 18, name: "Юрий", lastName: "Семенов", companyId: 6, post: "Дизайнер интерфейса"},
  {id: 19, name: "Елена", lastName: "Морозова", companyId: 2, post: "Менеджер проекта"},
  {id: 20, name: "Алексей", lastName: "Иванов", companyId: 9, post: "Аналитик"},
  {id: 21, name: "Ольга", lastName: "Кузнецова", companyId: 7, post: "Маркетолог"},
  {id: 22, name: "Иван", lastName: "Николаев", companyId: 4, post: "Программист"},
  {id: 23, name: "Евгений", lastName: "Васильев", companyId: 3, post: "Системный администратор"},
  {id: 24, name: "Татьяна", lastName: "Попова", companyId: 6, post: "Проектировщик"},
  {id: 25, name: "Александр", lastName: "Соколов", companyId: 8, post: "Инженер-конструктор"},
  {id: 26, name: "Екатерина", lastName: "Лебедева", companyId: 5, post: "Дизайнер"},
  {id: 27, name: "Наталья", lastName: "Иванова", companyId: 1, post: "Архитектор"},
  {id: 28, name: "Дмитрий", lastName: "Петров", companyId: 10, post: "Программист"},
  {id: 29, name: "Ирина", lastName: "Смирнова", companyId: 2, post: "Тестировщик"},
  {id: 30, name: "Сергей", lastName: "Козлов", companyId: 9, post: "Аналитик"},
  {id: 31, name: "Мария", lastName: "Морозова", companyId: 3, post: "Менеджер проекта"},
  {id: 32, name: "Павел", lastName: "Волков", companyId: 4, post: "Программист"},
  {id: 33, name: "Светлана", lastName: "Павлова", companyId: 8, post: "Менеджер"},
  {id: 34, name: "Андрей", lastName: "Семенов", companyId: 5, post: "Дизайнер"},
  {id: 35, name: "Анна", lastName: "Иванова", companyId: 6, post: "Разработчик"},
  {id: 36, name: "Юрий", lastName: "Николаев", companyId: 2, post: "Менеджер проекта"},
  {id: 37, name: "Елена", lastName: "Васильева", companyId: 7, post: "Маркетолог"},
  {id: 38, name: "Алексей", lastName: "Попов", companyId: 10, post: "Программист"},
  {id: 39, name: "Ольга", lastName: "Соколова", companyId: 1, post: "Аналитик"},
  {id: 40, name: "Иван", lastName: "Лебедев", companyId: 4, post: "Программист"},
  {id: 41, name: "Евгений", lastName: "Кузнецов", companyId: 9, post: "Технический директор"},
  {id: 42, name: "Татьяна", lastName: "Иванова", companyId: 8, post: "Менеджер"},
  {id: 43, name: "Александр", lastName: "Петров", companyId: 7, post: "Разработчик"},
  {id: 44, name: "Екатерина", lastName: "Смирнова", companyId: 3, post: "Дизайнер"},
  {id: 45, name: "Наталья", lastName: "Волкова", companyId: 6, post: "Менеджер проекта"},
  {id: 46, name: "Дмитрий", lastName: "Павлов", companyId: 2, post: "Тестировщик"},
  {id: 47, name: "Ирина", lastName: "Семенова", companyId: 10, post: "Аналитик"},
  {id: 48, name: "Сергей", lastName: "Иванов", companyId: 1, post: "Программист"},
  {id: 49, name: "Мария", lastName: "Николаева", companyId: 5, post: "Дизайнер интерфейса"},
  {id: 50, name: "Павел", lastName: "Васильев", companyId: 4, post: "Технический писатель"},
  {id: 51, name: "Светлана", lastName: "Попова", companyId: 7, post: "Маркетолог"},
  {id: 52, name: "Андрей", lastName: "Соколов", companyId: 9, post: "Архитектор"},
  {id: 53, name: "Анна", lastName: "Лебедева", companyId: 3, post: "Аналитик"},
  {id: 54, name: "Юрий", lastName: "Кузнецов", companyId: 8, post: "Разработчик"},
  {id: 55, name: "Елена", lastName: "Иванова", companyId: 2, post: "Менеджер проекта"},
  {id: 56, name: "Алексей", lastName: "Петров", companyId: 6, post: "Менеджер"},
  {id: 57, name: "Ольга", lastName: "Смирнова", companyId: 10, post: "Дизайнер"},
  {id: 58, name: "Иван", lastName: "Волков", companyId: 5, post: "Менеджер проекта"},
  {id: 59, name: "Евгений", lastName: "Павлов", companyId: 1, post: "Технический директор"},
  {id: 60, name: "Татьяна", lastName: "Семенова", companyId: 4, post: "Тестировщик"},
  {id: 61, name: "Александр", lastName: "Иванов", companyId: 7, post: "Разработчик"},
  {id: 62, name: "Екатерина", lastName: "Николаева", companyId: 3, post: "Дизайнер"},
  {id: 63, name: "Наталья", lastName: "Васильева", companyId: 9, post: "Менеджер проекта"},
  {id: 64, name: "Дмитрий", lastName: "Попов", companyId: 2, post: "Программист"},
  {id: 65, name: "Ирина", lastName: "Соколова", companyId: 8, post: "Аналитик"},
  {id: 66, name: "Сергей", lastName: "Лебедев", companyId: 6, post: "Архитектор"},
  {id: 67, name: "Мария", lastName: "Кузнецова", companyId: 10, post: "Дизайнер интерфейса"},
  {id: 68, name: "Павел", lastName: "Иванов", companyId: 1, post: "Программист"},
  {id: 69, name: "Светлана", lastName: "Петрова", companyId: 5, post: "Аналитик"},
  {id: 70, name: "Андрей", lastName: "Смирнов", companyId: 4, post: "Менеджер проекта"},
  {id: 71, name: "Анна", lastName: "Волкова", companyId: 7, post: "Маркетолог"},
  {id: 72, name: "Юрий", lastName: "Павлов", companyId: 9, post: "Архитектор"},
  {id: 73, name: "Елена", lastName: "Семенова", companyId: 2, post: "Программист"},
  {id: 74, name: "Алексей", lastName: "Иванов", companyId: 8, post: "Разработчик"},
  {id: 75, name: "Ольга", lastName: "Николаева", companyId: 6, post: "Менеджер"},
  {id: 76, name: "Иван", lastName: "Васильев", companyId: 3, post: "Дизайнер"},
  {id: 77, name: "Евгений", lastName: "Попов", companyId: 10, post: "Аналитик"},
  {id: 78, name: "Татьяна", lastName: "Соколова", companyId: 1, post: "Менеджер проекта"},
  {id: 79, name: "Александр", lastName: "Лебедев", companyId: 5, post: "Разработчик"},
  {id: 80, name: "Екатерина", lastName: "Кузнецова", companyId: 4, post: "Технический писатель"},
  {id: 81, name: "Наталья", lastName: "Иванова", companyId: 7, post: "Маркетолог"},
  {id: 82, name: "Дмитрий", lastName: "Петров", companyId: 9, post: "Программист"},
  {id: 83, name: "Ирина", lastName: "Смирнова", companyId: 2, post: "Тестировщик"},
  {id: 84, name: "Сергей", lastName: "Волков", companyId: 8, post: "Дизайнер"},
  {id: 85, name: "Мария", lastName: "Павлова", companyId: 6, post: "Аналитик"},
  {id: 86, name: "Павел", lastName: "Семенов", companyId: 3, post: "Менеджер проекта"},
  {id: 87, name: "Светлана", lastName: "Иванова", companyId: 10, post: "Аналитик"},
  {id: 88, name: "Андрей", lastName: "Николаев", companyId: 1, post: "Разработчик"},
  {id: 89, name: "Анна", lastName: "Васильева", companyId: 5, post: "Дизайнер интерфейса"},
  {id: 90, name: "Юрий", lastName: "Попов", companyId: 4, post: "Менеджер"},
  {id: 91, name: "Елена", lastName: "Соколова", companyId: 7, post: "Маркетолог"},
  {id: 92, name: "Алексей", lastName: "Лебедев", companyId: 9, post: "Разработчик"},
  {id: 93, name: "Ольга", lastName: "Кузнецова", companyId: 2, post: "Технический писатель"},
  {id: 94, name: "Иван", lastName: "Иванов", companyId: 8, post: "Продюсер"},
  {id: 95, name: "Екатерина", lastName: "Петрова", companyId: 1, post: "Аналитик"},
  {id: 96, name: "Дмитрий", lastName: "Смирнов", companyId: 5, post: "Разработчик"},
  {id: 97, name: "Ирина", lastName: "Васильева", companyId: 10, post: "Аналитик"},
  {id: 98, name: "Сергей", lastName: "Попов", companyId: 2, post: "Тестировщик"},
  {id: 99, name: "Мария", lastName: "Соколова", companyId: 6, post: "Дизайнер"},
  {id: 100, name: "Павел", lastName: "Лебедев", companyId: 3, post: "Менеджер"}
] as Employee[];
